#!/bin/sh

if [ "$TRAVIS_EVENT_TYPE" = "cron" ]
then
        exit 0
fi

cd src
gcc -o sqliteshell shell.c sqlite3secure.c -D_CRT_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -DNDEBUG -D_USRDLL -DTHREADSAFE=1 -DSQLITE_SOUNDEX -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_HAS_CODEC -DSQLITE_SECURE_DELETE -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE -DSQLITE_CORE -DSQLITE_ENABLE_EXTFUNC -DSQLITE_ENABLE_CSV -DSQLITE_ENABLE_SHA3 -DSQLITE_USE_URI -DSQLITE_USER_AUTHENTICATION -DCODEC_TYPE=CODEC_TYPE_AES256 -lpthread -ldl -lm

